# Generated by Django 4.2.4 on 2023-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hole',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
