# Generated by Django 4.2.4 on 2023-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='par',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='slope',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='course',
            name='stroke_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='tees',
            field=models.CharField(default='White', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='yards',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
