# Generated by Django 4.2.4 on 2023-08-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_holes_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holes',
            new_name='Hole',
        ),
    ]
