# Generated by Django 4.2.4 on 2023-08-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_holes_hole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hole',
        ),
    ]
