# Generated by Django 4.2.4 on 2023-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='hole',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hole',
            name='par',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='hole',
            name='stroke_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hole',
            name='yards',
            field=models.IntegerField(default=200),
        ),
    ]
