# Generated by Django 4.2.4 on 2023-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_hole_hole_alter_hole_par_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hole',
        ),
    ]
