# Generated by Django 4.2.4 on 2023-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('hole', models.IntegerField(default=1)),
                ('par', models.IntegerField(default=1)),
                ('yards', models.IntegerField(default=1)),
                ('adam', models.IntegerField()),
                ('alex', models.IntegerField()),
                ('jaime', models.IntegerField()),
                ('rich', models.IntegerField()),
                ('sandies', models.CharField(max_length=10)),
                ('round_number', models.IntegerField(default=1)),
            ],
        ),
    ]
