# Generated by Django 4.2.4 on 2023-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='par',
        ),
        migrations.RemoveField(
            model_name='round',
            name='yards',
        ),
        migrations.AddField(
            model_name='round',
            name='tees',
            field=models.CharField(default='White', max_length=7),
            preserve_default=False,
        ),
    ]
