# Generated by Django 4.2.4 on 2023-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_round_par_remove_round_yards_round_tees'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='match_col',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField><django.db.models.fields.IntegerField>', max_length=30, verbose_name='<django.db.models.fields.CharField><django.db.models.fields.CharField><django.db.models.fields.IntegerField>'),
        ),
    ]
