# Generated by Django 4.2.4 on 2023-08-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_hole_match_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='match_col',
        ),
    ]
