# Generated by Django 4.2.4 on 2023-08-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_hole_match_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='adam',
        ),
        migrations.RemoveField(
            model_name='round',
            name='alex',
        ),
        migrations.RemoveField(
            model_name='round',
            name='jaime',
        ),
        migrations.RemoveField(
            model_name='round',
            name='rich',
        ),
        migrations.RemoveField(
            model_name='round',
            name='sandies',
        ),
    ]
