# Generated by Django 4.2.4 on 2023-08-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_round_hole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adam', models.IntegerField()),
                ('round_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.round')),
            ],
        ),
    ]
