# Generated by Django 4.2.4 on 2023-08-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.hole'),
            preserve_default=False,
        ),
    ]
