# Generated by Django 4.2.4 on 2023-08-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_scoring_adam'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='alex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
