# Generated by Django 4.2.4 on 2023-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_scoring_alex'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='jaime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoring',
            name='rich',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
