# Generated by Django 4.2.4 on 2023-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_scoring_jaime_scoring_rich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('handicap_index', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='slope_rating',
            field=models.IntegerField(default=113),
        ),
    ]
