# Generated by Django 4.2.4 on 2023-08-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_player_hole_slope_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.player')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.scoring')),
            ],
        ),
    ]
