# Generated by Django 4.2.4 on 2023-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='adam_stable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoring',
            name='alex_stable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoring',
            name='jaime_stable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoring',
            name='rich_stable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
