# Generated by Django 4.2.4 on 2023-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_scoring_adam_to_par_scoring_alex_to_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='sandies',
            field=models.CharField(default='', max_length=10),
        ),
    ]
