# Generated by Django 4.2.4 on 2023-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_round_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='better_ball',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoring',
            name='match_play',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
