# Generated by Django 4.2.4 on 2023-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_scoring_better_ball_scoring_match_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoring',
            old_name='better_ball',
            new_name='better_ball_team_a',
        ),
        migrations.AddField(
            model_name='scoring',
            name='better_ball_team_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
